export { AppShell } from './AppShell';
export { SyntheticBanner, SYNTHETIC_BANNER_TEXT } from './SyntheticBanner';
export { RoleSwitcher } from './RoleSwitcher';
export { ClockReadout } from './ClockReadout';
export { ValidationReport } from './ValidationReport';
export { ErrorBoundary } from './ErrorBoundary';
export { useApp } from './useApp';
export type { AppExtras } from './useApp';
export { useContent } from './useContent';
export type { ContentApi, ContentVars } from './useContent';
export { usePractice, roleLabel, NOT_YET_ASSIGNED, NOT_YET_SECURED } from './usePractice';
export type { PracticeApi, OnDuty } from './usePractice';
export { useDemoNotes, getDemoNotes, setDemoNotes, DEMO_NOTES_KEY } from './demoNotes';
export { isoToLocalInput, localInputToIso, isoToLocalDate } from './timeInput';
export * from './routes';
